# Generated by Django 5.0.4 on 2024-04-28 01:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_manager", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
