# Generated by Django 5.0.4 on 2024-04-14 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                16, message="L'âge doit être supérieur à 15 ans."
                            )
                        ]
                    ),
                ),
                ("consentement", models.BooleanField(default=False)),
            ],
        ),
    ]
